### ISSUE TITLE
fix consistency between "data frame" and "dataframe"

### ISSUE THREAD

**Issue by zekiakyol** [aeturrell/python4DS#17]
The book uses both "data frame(s)" and "dataframe(s)" for non-object type (non-`DataFrame`) references.

- "data frame" example: <https://aeturrell.github.io/python4DS/exploratory-data-analysis.html#skimpy-for-summary-statistics>
- "dataframe" example:  <https://aeturrell.github.io/python4DS/exploratory-data-analysis.html#id2>

I can create a pull request to convert all "dataframe(s)" into "data frame(s) excluding `DataFrame`, if it is plausible.

**Comment by aeturrell** [comment]
That would be brilliant!
