### ISSUE TITLE
add `()` for inline functions

### ISSUE THREAD

**Issue by zekiakyol** [aeturrell/python4DS#18]
To increase readability, we might add `()` at the end of inline functions for example
- converting `sum comes with` into `sum() comes with` at <https://aeturrell.github.io/python4DS/workflow-basics.html#calling-functions>
- converting `pd.read_csv` to `pd.read_csv()` at <https://aeturrell.github.io/python4DS/data-import.html#reading-data-from-a-file>

I can create a pull request to convert, if it is plausible.

**Comment by aeturrell** [comment]
That would be fantastic! Thank you!

**Comment by zekiakyol** [comment]
You are welcome!
