### ISSUE TITLE
Check R for Data Science link

### ISSUE THREAD

**Issue by harrietrs** [aeturrell/python4DS#22]
👋 @aeturrell

Very small issue- I wondered if the link in the introduction to https://r4ds.had.co.nz/ rather than http://r4ds.hadley.nz/ (which is the more up-to-date url) was deliberate? i.e. is there something specific about this content that served as inspiration?

If not, it's an easy fix 😋

**Comment by aeturrell** [comment]
Hi Harriet,

Great to hear from you. This was fixed in #15 but the website hasn't been updated yet!
