### ISSUE TITLE
Issue on page /data-visualise.html

### ISSUE THREAD

**Issue by durraniu** [aeturrell/python4DS#6]
I ran the seaborn code but it threw an error. Probably because the package was updated.

`so.Plot(mpg, x="displ", y="hwy").add(so.Scatter())`
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
c:\Users\umair\Documents\testing.py in <cell line: 1>()
----> [12](file:///c%3A/Users/umair/Documents/testing.py?line=11) so.Plot(mpg, x="displ", y="hwy").add(so.Scatter())

AttributeError: module 'seaborn.objects' has no attribute 'Scatter'
```

It runs if I replace `.Scatter` with `.Dots` or `.Dot`. 

Moreover, code with `move` parameter also throws error, both for the bar plot and the jittered scatter plot.

**Comment by aeturrell** [comment]
Thanks for flagging this; **seaborn** has recently been updated which led to the issues. This should be fixed in [5c8c128](https://github.com/aeturrell/python4DS/commit/5c8c1283ca4b7b7918bb0bb0ac6135721135db47).
